# Generated by Django 4.0.3 on 2022-03-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=10)),
            ],
        ),
    ]
