# Generated by Django 4.0.3 on 2022-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_category_images_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='employerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('job_Title', models.CharField(max_length=100)),
                ('title_Position', models.CharField(max_length=50)),
                ('personal_Email', models.CharField(max_length=100)),
                ('phone_Number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=10)),
                ('account_Holder_Name', models.CharField(max_length=100)),
                ('bank_Name', models.CharField(max_length=100)),
                ('branch_Name', models.CharField(max_length=100)),
                ('account_Number', models.CharField(max_length=500)),
                ('IFSC_Code', models.CharField(max_length=100)),
                ('signIn_Email', models.CharField(max_length=100)),
                ('singnIn_Password', models.CharField(max_length=10)),
            ],
        ),
    ]
