# Generated by Django 4.0.3 on 2022-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_employerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerdetails',
            old_name='singnIn_Password',
            new_name='signIn_Password',
        ),
        migrations.AddField(
            model_name='employerdetails',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
