# Generated by Django 4.0.3 on 2022-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_rename_singnin_password_employerdetails_signin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdetails',
            name='photo',
            field=models.ImageField(null=True, upload_to='employees_photo'),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='signIn_Password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
