# Generated by Django 4.0.3 on 2022-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_workassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassign',
            name='task',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
