# Generated by Django 4.0.3 on 2022-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_workassign_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassign',
            name='work_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
