# Generated by Django 4.0.3 on 2022-03-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0011_employerdetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('current_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ended_time', models.TimeField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.employerdetails')),
            ],
        ),
    ]
