# Generated by Django 4.0.3 on 2022-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_an_estimate',
            name='checkout',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
