# Generated by Django 4.0.3 on 2022-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_get_an_estimate_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('what_are_you_looking_for', models.CharField(max_length=20)),
            ],
        ),
    ]
